spring.application.name=userapp
server.address=0.0.0.0
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/userapp
spring.datasource.username=root
spring.datasource.password=pass@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
file.upload-dir=D:/spring boot/UserApp/UserApp/uploads/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/farm2home
# Google OAuth Client ID (Replace with your actual Web Client ID)
google.client-id=159078840279-7slmnqaleckksrrtr1i35lfnqj0g23v0.apps.googleusercontent.com
